trigger:
  branches:
    include:
    - release
    - develop
  paths:
    exclude:
    - README.md
    - .gitignore
  
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  variables:
    BuildPlatform: Any CPU
    BuildConfiguration: Release
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - bash: docker image build . -t thr-step-ca
  - bash: docker image save thr-step-ca -o - | gzip > $(Build.ArtifactStagingDirectory)/thr-step-ca.tar.gz

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactType: container
      artifactName: package
