trigger:
  branches:
    include:
    - release
    - develop
  paths:
    exclude:
    - README.md
    - .gitignore
  
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - bash: docker image build . -t thr-stepca-azure:$(Build.BuildNumber)
  - bash: docker image save thr-stepca-azure:$(Build.BuildNumber) -o $(Build.ArtifactStagingDirectory)/thr-stepca-azure.tar

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/thr-stepca-azure.tar
      artifactType: container
      artifactName: docker
