trigger:
  branches:
    include:
    - release
    - develop
  paths:
    exclude:
    - README.md
    - .gitignore

pool:
  vmImage: 'windows-2019'
  
jobs:
- job: Build
  workspace:
    clean: all
  variables:
    BuildPlatform: Any CPU
    BuildConfiguration: Release
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'

  - task: VSBuild@1
    inputs:
      solution: TexasHealth.Azure.Infrastructure.StepCA.sln
      vsVersion: latest
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      maximumCpuCount: true
      msbuildArchitecture: x64

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactType: container
      artifactName: package
